version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: roman-converter-backend-dev
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app
    networks:
      - app-network
 k
    command: ["python", "app.py"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: roman-converter-frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    command: ["npm", "start"]

networks:
  app-network:
    driver: bridge
